### ISSUE TITLE
Worldmodels invisible on other players, but visible on the client in thirdperson

### ISSUE THREAD

**Issue by iiangre** [nosoop/SM-TFCWXBaseAttributes#18]
Had this issue for bit, custom worldmodels on other players do not show up but you can see the outline of the weapon for the seconds teammates have outlines when you respawn.

Custom worldmodels are completely visible on yourself when in third person, I have no other plugins than a thirdperson plugin and the ones needed for CWX.  It feels like it's not a problem with CWX, but I'm unsure what would be the stem of it.

**Comment by nosoop** [comment]
Additional functionality to make wearables "validated" for visibility to other clients is not part of the plugin to be in line with Valve's previous guidelines on economy items.

You'd need to find an additional plugin to mark wearables as validated, and I would not provide support for that out of policy.

But since the VScript update exposes the very same functionality to mappers, there probably isn't much point to avoid including it these days.

**Comment by iiangre** [comment]
I see, thanks for the reply.

**Comment by iiangre** [comment]
I see, thanks for the reply.
